### ISSUE TITLE
Events from Liberal Arts

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Global-Studies#20]
https://liberalarts.temple.edu/events/global-studies/rss
https://liberalarts.temple.edu/events/global-studies/json
https://liberalarts.temple.edu/events/global-studies/csv

**Comment by tu-chill** [comment]
zac degrade gracefully when there are no events, or one event

**Comment by tu-chill** [comment]
We are going to run into this problem  a lot in the near future

**Comment by tu-chill** [comment]
Do we have a design for when there is only one event?

Do we have a plan for when there are no events?

**Comment by ZMcGroarty** [comment]
I have some ideas, I'll get those down tomorrow.



On Wed, Feb 15, 2017 at 7:21 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we have a design for when there is only one event?

Do we have a plan for when there are no events?

**Comment by ZMcGroarty** [comment]
Is it possible to have the events/news jekyll system just pull the 3 most recent (even if unrelated) events/news items rather than creating some odd placeholder? If so, I’d absolutely prefer to do that so the experience is generally the same each time.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Feb 15, 2017, at 7:23 PM, Zachary McGroarty <tug28959@temple.edu<mailto:tug28959@temple.edu>> wrote:


I have some ideas, I'll get those down tomorrow.



On Wed, Feb 15, 2017 at 7:21 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we have a design for when there is only one event?

Do we have a plan for when there are no events?

**Comment by pixelyunicorn** [comment]
Sure, I just need a fallback feed URL

**Comment by tu-chill** [comment]
https://github.com/TULiberalArts/Global-Studies/issues/19

A good design decision has been made - screenshot is in issue #19
